### PR TITLE
Flip the bloody arrow

### LINKED ISSUE #313: Flip arrow during view story in all-stories and map view
image

Note that the upper left arrow is pointing right, that doesn't make sense. Flip the arrow.

### PR DESCRIPTION
**Pull request by liu-jeffrey**
Flips the arrow. Closes #313 

image

### CODE REVIEW

**Review by hanlinc27 — APPROVED** [review]
tumblr_2557180d046964053d2c8451bc8229f6_8fa62315_500

**Review by nimwijetunga — APPROVED** [review]
Should we do this for the map page (pin preview) as well @hanlinc27 @jenna-hirji?

**Comment by nimwijetunga** [comment]
@liu-jeffrey I spoke offline with jenna you should be good to merge this we'll discuss the map page on saturday (and whether to flip the arrow or not there)

**Comment by liu-jeffrey** [comment]
OOps i think this change flips the arrow on stories on the map page as well since they both use the same component.

**Pull request merged**
