### PR TITLE
Fix: Map Pin Placement

### LINKED ISSUE #334: Map pins showing in ocean
image

### PR DESCRIPTION
**Pull request by Shehryar21**
closes #334 

image

Difficult problems require simple solutions.

### CODE REVIEW

**Review by nimwijetunga — APPROVED** [review]
nice work lgtm

**Review by hanlinc27 — APPROVED** [review]

**Comment by hanlinc27** [comment]
With this change, the pin cluster pins are the same size as the individual pins which we don't want visually though?

**Comment by nimwijetunga** [comment]
I think it's better than having pins in the water though @jenna-hirji thoughts?

**Comment by hanlinc27** [comment]
@nimwijetunga @Shehryar21 try changing the resting states for pin in `Pin.tsx` to something slightly smaller than L.Point(39,48) if that's your cluster size.

**Comment by Shehryar21** [comment]
I can change the cluster size to whatever we want. What is the size we want?

**Comment by hanlinc27** [comment]
> I can change the cluster size to whatever we want. What is the size we want?

Let's just use the Figma hover state: 
width: 48px;
height: 57.93px;

**Pull request merged**
