### PR TITLE
fix Safari pin preview issues

### LINKED ISSUE #359: Pin Preview Not Showing on Safari
No idea whats causing this issue

### PR DESCRIPTION
**Pull request by Shehryar21**
Popup not showing up on Safari is a known issue in leaflet. Following are some the references to the issues:
https://github.com/Leaflet/Leaflet/issues/7255
https://github.com/PaulLeCam/react-leaflet/issues/790
https://github.com/Leaflet/Leaflet/issues/7331

Closes #359

### CODE REVIEW

**Review by nimwijetunga — CHANGES_REQUESTED** [review]
I get a bunch of wack errors when trying to load the map on chrome (i'm on linux):

image

**Comment by Shehryar21** [comment]
> I get a bunch of wack errors when trying to load the map on chrome (i'm on linux):
> 
> image

Did you try deleting your node_modules and cache and then running yarn to install the downgraded version?

**Comment by Shehryar21** [comment]
Wait yeah I am getting these errors as well. Dont review this PR for now sorry.

**Comment by hanlinc27** [comment]
Instead of downgrading have you tried the fix here: https://github.com/domoritz/leaflet-locatecontrol/issues/280

**Comment by Shehryar21** [comment]
> Instead of downgrading have you tried the fix here: [domoritz/leaflet-locatecontrol#280](https://github.com/domoritz/leaflet-locatecontrol/issues/280)

I did not understand where to add the tap:false thing

**Comment by hanlinc27** [comment]
image
This actually seems to fix the safari bug for me

**Comment by Shehryar21** [comment]
> image
> This actually seems to fix the safari bug for me

Oh yes wow. This fixes the issue for me as well. I hope this doesnt break anything else tho

**Review by hanlinc27 — APPROVED** [review]
https://leafletjs.com/reference-1.7.1.html#map-tap
`tap: Enables mobile hacks for supporting instant taps (fixing 200ms click delay on iOS/Android) and touch holds (fired as contextmenu events).`

**Review by nimwijetunga — APPROVED** [review]
Confirmed that the behaviour is fine on chrome/firefox so as long as you tested safari (I don't have it) it should be good to merge

**Pull request merged**
